#!/bin/bash
yarn export

# add .nojekyll to static build so that github-pages won't ignore _next folder
touch out/.nojekyll

# add CNAME file to static build
echo "greggw.com" >> out/CNAME

# force push the contents of the out/ directory on the develop branch to origin/master
git push origin `git subtree split --prefix out/ develop`:master --force

